Remove deprecated macOS and Linux autostart configurations; introduce systemd service for OTP auto-connect and update related scripts for improved functionality and logging. Remove deprecated autostart and plist files; implement systemd service for OTP auto-connect and enhance credential retrieval methods in the application. Update GitHub Actions workflow to disable JSCPD, MyPy, Pylint, and Hadolint validations; refactor main.py for improved readability and consistency in string formatting; enhance error logging; and modify vpn-connect script for better variable handling.

diff --git a/vpn-connect b/vpn-connect
--- a/vpn-connect
+++ b/vpn-connect
@@ -1,59 +1,17 @@
 #!/usr/bin/env bash
-ip route | grep default | awk '{print $3}' > /tmp/route
 
-uname=$(uname)
-username=$(cat ./username)
+# Wait for the service on port 8009 to be up
+while ! nc -z localhost 8009; do
+  echo "Waiting for service on port 8009 to be up..."
+  sleep 2  # Wait 2 seconds before retrying
+done
 
-key=$(pass show redhat.com/associate-password | tr -d '\n')
+vpn=$(pass show redhat.com/nm-uuid | tr -d '\n')
+response=$(curl -s "http://localhost:8009/get_creds?context=associate&headless=false")
+creds=$(echo "$response" | tr -d '"' | tr -d '\n')  # Remove quotes from the response
+pw=$(echo "$creds" | cut -d',' -f2)
 
-if [ "$key" == "" ]; then
-    key=$(cat ./key)
-fi
-
-token=$(./getpw)
-
-if [ "$uname" == "Darwin" ]; then
-
-    sleep 3
-
-    pgrep -u "$(whoami)" Viscosity
-    while [[ $? -eq 0 ]]; do
-        osascript -e 'quit app "Viscosity"'
-        sleep 3
-        pgrep -u "$(whoami)" Viscosity
-    done
-
-    connfile="$HOME/Library/Application Support/Viscosity/OpenVPN/1/config.conf"
-    sed -i '' "s#auth-user-pass#auth-user-pass /tmp/vpnpw#g" "$connfile"
-
-    pgrep -u "$(whoami)" Viscosity
-    while [[ $? -eq 1 ]]; do
-        sleep 2
-        /Applications/Viscosity.app/Contents/MacOS/Viscosity &
-        sleep 2
-        pgrep -u "$(whoami)" Viscosity
-    done
-
-    sleep 5
-
-    echo "$username" > /tmp/vpnpw
-    echo "$key$token" >> /tmp/vpnpw
-    echo "$key$token"
-    osascript -e "tell application \"Viscosity\" to connect \"Red Hat Global VPN\""
-    
-    sleep 5
-
-    sed -i '' "s#auth-user-pass /tmp/vpnpw#auth-user-pass#g" "$connfile"
-    cat /tmp/vpnpw
-    rm /tmp/vpnpw
-
-else
-
-    vpn=$(cat ./uuid)
-    echo "vpn.secrets.password:$key$token" > /tmp/vpnpw
-    sudo nmcli con up uuid $vpn passwd-file /tmp/vpnpw
-    sudo rm -f /tmp/vpnpw
-
-fi
-
-
+echo "vpn.secrets.password:$pw" | sudo tee /tmp/vpnpw > /dev/null
+sudo cat /tmp/vpnpw
+sudo nmcli con up uuid "$vpn" passwd-file /tmp/vpnpw
+sudo rm -f /tmp/vpnpw
